services:
  app_todo:
    build: ToDo
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL:
      DB_USER:
      DB_PASSWORD:
    restart: always
    depends_on:
      todo:
        condition: service_healthy
  todo:
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD:
      MYSQL_DATABASE: todocrud
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
